### ISSUE TITLE
still in progress ,or dead?

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [martinrotter/qt-material-stylesheet#2]
Hi - want to ask, if you have any progress on this project
or if you stop working on stylesheet for QWidget?

**Comment by martinrotter** [comment]
I did not even start working. :) No time and need, I only created this repo to remind myself that I could write something like that one day.

**Comment by Jorgen-VikingGod** [comment]
Ok I see. That would be awesome to have such a stylesheet set for QWidgets.
In the case you do not want to use QML for your application.

Maybe I will start once with this - but I have less time too :/

**Comment by martinrotter** [comment]
Definitely.
